version: '3' #docker version
services:
  www:
    image: php:apache
    volumes:
      - ./www:/var/www/html #bu dizindeki her şeyi /var/www/html dizinine bağla
    ports:
      - "8001:80"
  mongo:
    image: mongo
    ports:
      - 8003:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME = root
      - MONGO_INITDB_ROOT_PASSWORD = root
    volumes:
      - mongo_data:/data/db # MongoDB verilerini saklamak için bir Docker volume'ı
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    


volumes:
  esdata:
  mongo_data:

      

  